- Intervention 0:
  id: 0
  name: Basecase
  testing_groups:
    - group 1:
      id: 1
      name: Base 1
      begin_cycle: 2
      end_cycle: 1000
      monthly_testing_uptake: 0.002041034
      # see Updated LTBI Estimate using nativity and race 20140416.xls
      test_choice_pos: Infected Testing TST
      test_choice_neg: Uninfected Testing TST
      treatment_choice_pos: LTBI 6m INH - Month 1
      treatment_choice_neg: FP LTBI 6m INH - Month 1
      criteria:
        - chain_name: Natural death
          state_names:
            - Life
    - group 2:
      id: 2
      name: Base 2
      begin_cycle: 2
      end_cycle: 1000
      monthly_testing_uptake: 0.002041034
      # see Updated LTBI Estimate using nativity and race 20140416.xls
      test_choice_pos: Infected Testing QFT
      test_choice_neg: Uninfected Testing QFT
      treatment_choice_pos: LTBI 6m INH - Month 1
      treatment_choice_neg: FP LTBI 6m INH - Month 1
      criteria:
        - chain_name: Natural death
          state_names:
            - Life