- Intervention 3:
  id: 0
  name: 10x in FB + Med risk factor (QFT/3HP)
  testing_groups:
    - group 1:
      id: 1
      name: Base 1
      begin_cycle: 2
      end_cycle: 1000
      monthly_testing_uptake: 0.002041034
      # see "current treatment levels xls"
      test_choice_pos: Infected Testing TST
      test_choice_neg: Uninfected Testing TST
      treatment_choice_pos: LTBI 6m INH - Month 1
      treatment_choice_neg: FP LTBI 6m INH - Month 1
      criteria:
        - chain_name: Natural death
          state_names:
            - Life
    - group 2:
      id: 2
      name: Base 2
      begin_cycle: 2
      end_cycle: 1000
      monthly_testing_uptake: 0.002041034
      # see "current treatment levels xls"
      test_choice_pos: Infected Testing QFT
      test_choice_neg: Uninfected Testing QFT
      treatment_choice_pos: LTBI 6m INH - Month 1
      treatment_choice_neg: FP LTBI 6m INH - Month 1
      criteria:
        - chain_name: Natural death
          state_names:
            - Life
    - group 3:
      id: 3
      name: Base 3
      begin_cycle: 2
      end_cycle: 1000
      monthly_testing_uptake: 0.036738612
      # see "current treatment levels xls"
      test_choice_pos: Infected Testing QFT
      test_choice_neg: Uninfected Testing QFT
      treatment_choice_pos: LTBI RTP - Month 1
      treatment_choice_neg: FP LTBI RTP - Month 1
      criteria:
        - chain_name: Citizen
          state_names:
            - Naturalized citizen
            - Not a citizen
            - Born abroad of American parents
    - group 4:
      id: 4
      name: Base 4
      begin_cycle: 2
      end_cycle: 1000
      monthly_testing_uptake: 0.036738612
      # see "current treatment levels xls"
      test_choice_pos: Infected Testing QFT
      test_choice_neg: Uninfected Testing QFT
      treatment_choice_pos: LTBI RTP - Month 1
      treatment_choice_neg: FP LTBI RTP - Month 1
      criteria:
        - chain_name: Medical risk factor
          state_names:
            - Medical risk factor


# === Gen Pop ===
# Untested:  22844
# Tested:  2690
# % Tested:  0.11775521
# === FB ===
# Untested:  13005
# Tested:  1570
# % Tested:  0.1207228
# === MRF ===
# Untested:  3002
# Tested:  1183
# % Tested:  0.39407063
# Reseeding random data
# sizes: 155 25534 19 4